services:
  web:
    build: .
    container_name: rbsite_app
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/rbsite/files
      - ./vendor:/var/www/html/rbsite/vendor
      - ./rbsite.conf:/etc/apache2/sites-available/000-default.conf
    restart: unless-stopped
